# spring.datasource.url=jdbc:mysql://localhost:3306/travelease
# spring.datasource.username=root
# spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Let Spring Boot auto-detect the dialect based on the URL
# spring.jpa.properties.hibernate.dialect is no longer needed

gemini.api.key=AIzaSyDnpu3QfPwEngvCv3IuQxSAZmeOgmQsNTg